DROP TABLE USER_ROLE;
DROP TABLE ROLE_PERMISSION;
DROP TABLE USER_CREDIT_CARD_INFO;
DROP TABLE USER_SECONDARY_CREDIT_CARD_INFO;

DROP TABLE USER;
DROP TABLE ROLE;
DROP TABLE PERMISSION;
DROP TABLE CREDIT_CARD_INFO;
