INSERT INTO USER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, CITY, COUNTRY, ENABLED, GENDER, LANGUAGE, OCCUPATION, EDUCATION, BLOOD_TYPE, MARITAL_STATUS, RELIGION, BIRTH_DATE, PHONE_NUMBER) VALUES (1, 'user', 'password',  'Serkan', 'OZAL', 'Ankara', 'Turkey', 1, 1, 1, 300, 'MASTER', 1, 'SINGLE', 'MUSLIM', '1986-09-15', '+901234567890');

INSERT INTO ROLE (ID, NAME) VALUES(1, 'Member');
INSERT INTO ROLE (ID, NAME) VALUES(2, 'Admin');

INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 1);
INSERT INTO USER_ROLE (USER_ID, ROLE_ID) VALUES (1, 2);

INSERT INTO CREDIT_CARD_INFO (ID, CREDIT_CARD_NUMBER, SECURITY_CODE, EXPIRATION_DATE) VALUES(1, '1234-5678-9000', '123', '2020-12-31');
INSERT INTO CREDIT_CARD_INFO (ID, CREDIT_CARD_NUMBER, SECURITY_CODE, EXPIRATION_DATE) VALUES(2, '9876-5432-1000', '456', '2030-12-31');

INSERT INTO USER_CREDIT_CARD_INFO (USER_ID, CREDIT_CARD_INFO_ID) VALUES (1, 1);
INSERT INTO USER_SECONDARY_CREDIT_CARD_INFO (USER_ID, CREDIT_CARD_INFO_ID) VALUES (1, 2);

INSERT INTO ACCOUNT_INFO (ID, IBAN, BANK_CODE, ACCOUNT_NO, CUSTOMER_NO) VALUES(1, '123456789', '1234', '56789', '13579');

INSERT INTO USER_ACCOUNT_INFO (USER_ID, ACCOUNT_INFO_ID) VALUES (1, 1);

INSERT INTO PERMISSION (NAME) VALUES('MEMBER_GET_PERM');
INSERT INTO PERMISSION (NAME) VALUES('MEMBER_LIST_PERM');
INSERT INTO PERMISSION (NAME) VALUES('MEMBER_UPDATE_PERM');
INSERT INTO PERMISSION (NAME) VALUES('MEMBER_DELETE_PERM');
INSERT INTO PERMISSION (NAME) VALUES('ADMIN_GET_PERM');
INSERT INTO PERMISSION (NAME) VALUES('ADMIN_LIST_PERM');
INSERT INTO PERMISSION (NAME) VALUES('ADMIN_UPDATE_PERM');
INSERT INTO PERMISSION (NAME) VALUES('ADMIN_DELETE_PERM');

INSERT INTO ROLE_PERMISSION (SELECT r.ID, p.ID FROM PERMISSION p, ROLE r WHERE p.NAME LIKE 'MEMBER_%' AND r.NAME = 'Member');
INSERT INTO ROLE_PERMISSION (SELECT r.ID, p.ID FROM PERMISSION p, ROLE r WHERE p.NAME LIKE 'ADMIN_%' AND r.NAME = 'Admin');

COMMIT;
